<?php
echo "";
?>
<!DOCTYPE html>																			
	<html>																							<!-- открытие HTML -->
		<head>																						<!-- загрузка методанных -->
		 <link rel="stylesheet" href="MASTER.css">													<!-- подключение CSS -->
			<title>																					
				CCS+HTML=АД
			</title>																				<!-- имя сайта -->
			<link rel="shortcut icon" href="image/logologo.png" type="image/logologo.png">
		</head>
		
		<body>																						<!-- открытие туловища -->
			<header>																				<!-- открытие шапка -->
				<div class="logo">																	<!-- блок отвечающий за лого -->
					<img src="imeges/logo.png" class="logo-img">									<!-- вставка лого -->
					<span class="logo-title">
						 My-Giro
					</span>
				</div>
				<div class="hor-menu">																<!-- меню -->
				<ul>
					<li>
						<a href="">
							Главная																	<!-- на главную -->
						</a>
					</li>
					<li>
						<a href="1">
							+7 351 111 22 33														<!-- номер для вызова -->
						</a>
					</li>
				<ul>
				</div>
			</header>
																									<!-- основной контент -->
			<br/><br/><br/>
			<div class="wrapper">																	<!-- блок Преимущества компании -->
				<div class="content">
					
					<p>
						<h2>
							Преимущества компании
						</h2>
						<li>
							Мы обслуживаем одинаково качественно как своих гарантийных клиентов, так и сторонние заказы.
						</li>
						<li>
							Если деталь сломалась — в нашем центре ее не будут ремонтировать, а сразу заменят на новую.
						</li>
						<li>
							мы работаем с крупной сетью сервисных центров, ее филиалы находятся в 70 городах России.
						</li>
						<li>
							Гарантия действует в течении 3 лет!
						</li>
					</p>
					<p>
						<h2>
							Блок, содержащий особенности гироскутеров, электросамокотов и сигвеев:
						</h2>
						<li>
							Электросамокат - современный вариант простого самоката. Для того чтобы на нем кататься, нужно всего один раз оттолкнуться ногой от земли, обеспечив стартовое ускорение. Дальше устройство будет везти хозяина самостоятельно за счет встроенного электромотора. Если выбирать между моноколесом или электросамокатом, последний будет гораздо безопаснее в эксплуатации за счет наличия 2 колес (т.е. 2 точек опоры) и ручки для опоры руками.
						</li>
						<li>
							Гироскутер представляет собой конструкцию из 2 колес, расположенных по бокам от наездника и соединенных поперечной планкой-корпусом. Внутри корпуса располагаются электродвигатели, аккумуляторные батареи и гироскопы, поддерживающие в горизонтальном положении площадку для ног.

Гироскутеры никогда не оснащаются рукоятками для рук. Устройства из 2 колес, поперечной площадки и рулевого столба называются сигвеями и управляются манипуляциями руками.

Особенность управления гироскутером состоит в том, что для движения вперед наезднику необходимо наклониться вперед. Для торможения или движения назад - наклониться назад. Для поворота нужно наклонять корпус в правую или левую сторону.
						</li>
						<li>
							Сигвей - средство передвижения для одного человека, которое держит равновесие с помощью специальной автобалансирующей системы. Это своеобразный электрический скутер, самостоятельно удерживающий равновесие. Сигвеи бесшумны в работе, не загрязняют окружающую среду, работают на электрической энергии, накопленной батареей аккумуляторов
						</li>
					</p>
				</div>
			</div>
			<div class="sidebar">
				<div class="wrapper">
					
					
					
							<div class="container"> 
								<input type="radio" id="blue" name="color" />
								<label for="blue">Гироскутер</label>
								<input type="radio" id="red" name="color"/>
								<label for="red">Сигвей</label>
								<input type="radio" id="green" name="color"/>
								<label for="green">Электросамокат</label>
								<input type="radio" id="reset" name="color"/>
								<label for="reset">все</label>
								
								
								
					<table>																			<!-- Таблица с продукцией -->
						<colgroup>																	
							<col span="2" style="background:Khaki">
							<col style="background-color:LightCyan">
						</colgroup>
						
						<tr>																		<!-- Шапка таблици -->
							<th class="white">Фото</th>
							<th class="yellow">Название</th>
							<th class="white">Цена</th>
							<th class="yellow">Вид</th>
						</tr>
						<tr class="tile blue">																		<!-- Откр основного сод таблици -->
							<td class="white"><img src="imeges/3009.750x0-1000x1000.jpg" class="table-img"></td>
							<td class="yellow">Smart Balance 6.5" Ver. 1</td>
							<td class="white">8990</td>
							<td class="yellow">Гироскутер</td>
						</tr>
						<tr class="tile blue">
							<td class="white"><img src="imeges/foto-kiwano-ko-x-aver-sport-red-4-376x430.jpg" class="table-img"></td>
							<td class="yellow">KIWANO KO-X ES03</td>
							<td class="white">18900</td>
							<td class="yellow">Гироскутер</td>
						</tr>
						<tr class="tile red">
							<td class="white"><img src="imeges/1-1659f38c-1000x1000.jpg" class="table-img"></td>
							<td class="yellow">Minirobot Mini PRO 36V Белый</td>
							<td class="white">15990</td>
							<td class="yellow">Сигвей</td>
						</tr>
						<tr class="tile red">
							<td class="white"><img src="imeges/xiaomi-ninebot-mini-giroskuter-1.jpg" class="table-img"></td>
								<td class="yellow">Xiaomi Ninebot Mini</td>
								<td class="white">22900</td>
								<td class="yellow">Сигвей</td>
							</tr>
							<tr class="tile red">
								<td class="white"><img src="imeges/eb0168ec488d7999f334be39db46e3c2-1000x1000.jpg" class="table-img"></td>
								<td class="yellow">Hili E+</td>
								<td class="white">39900</td>
								<td class="yellow">Сигвей</td>
							</tr>
							<tr class="tile green">
								<td class="white"><img src="imeges/e-scooter-3-1000x1000.jpg" class="table-img"></td>
								<td class="yellow">Yamato PES MINI</td>
								<td class="white">15900</td>
								<td class="yellow">Электросамокат</td>
							</tr>
							<tr class="tile green">
								<td class="white"><img src="imeges/772888105_w640_h640_elektrosamokat-kugoo-s3.jpg" class="table-img"></td>
								<td class="yellow">KUGOO S2 (Jilong)</td>
								<td class="white">14900</td>
								<td class="yellow">Электросамокат</td>
							</tr>
						</table>
						</div>
					</div>
				
				
				
				</div>
				
				
				
				<div class="wrapper">																<!-- Слайдер -->
				  <div class="carousel-wrapper">
						<span id="item-1"></span>
						<span id="item-2"></span>
						<span id="item-3"></span>
						<div class="carousel-item item-1">											<!-- 1й элемент слайдера -->
							<p>Здесь будет ваш текст.1</p>
							<a class="arrow arrow-prev" href="#item-3"></a>
							<a class="arrow arrow-next" href="#item-2"></a>
						</div>
						<div class="carousel-item item-2">											<!-- 2й элемент слайдера -->
							<p>Здесь будет ваш текст.2</p>
							<a class="arrow arrow-prev" href="#item-1"></a>
							<a class="arrow arrow-next" href="#item-3"></a>
						</div>
						<div class="carousel-item item-3">											<!-- 3й элемент слайдера -->
							<p>Здесь будет ваш текст.3</p>
							<a class="arrow arrow-prev" href="#item-2"></a>
							<a class="arrow arrow-next" href="#item-1"></a>
						</div>
					</div>
				</div>
				<div class="wrapper">																<!-- блок содержащий информацию о консультантах -->
					<div class="content">
					
						<p>
							<h2>
								Блок, содержащий информацию о консультантах:
							</h2>
							<li>
								Мы обслуживаем одинаково качественно как своих гарантийных клиентов, так и сторонние заказы.
							</li>
							<li>
								Если деталь сломалась — в нашем центре ее не будут ремонтировать, а сразу заменят на новую.
							</li>
							<li>
								мы работаем с крупной сетью сервисных центров, ее филиалы находятся в 70 городах России.
							</li>
							<li>
								Гарантия действует в течении 3 лет!
							</li>
						</p>
						<p>
							<h2>
								Блок, содержащий полезную информацию:
							</h2>
							<li>
								Чтобы работать в наших магазинах нужно знать каждую модель, её плюсы и минусы и уметь ездить на ней. Да, это долго, и кто-то скажет, что неэффективно. Но так мы гарантированно получаем сотрудника, который разбирается в каждом товаре и сможет по-настоящему помочь покупателю, а не “впихнуть” ему, что-нибудь подороже.
							</li>
						</p>
					</div>
				</div>
				<div class="wrapper">																<!-- блок содержащий краткую информацию о компании и форму для подписки на email-рассылки -->
					<div class="content">
						<h2>
							Блок, содержащий краткую информацию о компании и форму для подписки на email-рассылки
						</h2>
						<li>
							Наш магазин работает с 2016 года. Мы представлены в таких городах как Екатеринбург, Москва и Челябинск и многие другие. В среднем мы отправляем по 15-20 заказов в день в разные города и регионы по всей России.
						</li>
						<li>
							Мы имеем свои сервисные центры и собственных мастеров, благодаря которым, выполняем гарантийные работы качественно и в срок. Так же вы можете обратиться к нам с любой проблемой. Мастера выполнят диагностику и выполнят ремонт.
						</li>
						<div class="subscribe">
							<a href="2">
							<img src="imeges/subscribe.png" class="subscribe-img">
							</a>
						</div>
					</div>
				</div>
			
		</body>
	</html>